# Generated by Django 4.0.6 on 2022-08-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('HP', 'High Priority'), ('MP', 'Medium Priority'), ('LP', 'Low Priority')], default='MP', max_length=2)),
            ],
        ),
    ]
